declare-option -hidden str run_in_pane_result

define-command run-in-pane \
    -params 1 \
    -docstring "
        Run a shell command inside a temporary tmux pane and store its output in a Kakoune option.

        The command is executed in a new tmux pane. Its standard output is captured
        and stored in the buffer-local option `run_in_pane_result`, which can then
        be used by other commands.

        Useful for integrating interactive tools (e.g. fzf, ranger) into Kakoune.
    " %{
    evaluate-commands %sh{
        run_cmd="$1"
        out_cmd="${2}"
        channel=$(mktemp)
        tmux wait-for -S $channel 2>/dev/null
        tmux popup -h 90% -w 90% -d "$PWD" -E "$run_cmd > \"$channel\"; tmux wait-for -S $channel"
        output=$(cat "$channel")
        rm "$channel"
        if [ -n "$output" ]; then
            printf "set-option buffer run_in_pane_result '%s'\n" "$output"
        fi
    }
}

define-command fzf-file -docstring "Search files using fzf and open match" %{
    try %{
        run-in-pane "fzf --preview 'cat {}'"
        edit -existing %opt{run_in_pane_result}
        unset-option buffer run_in_pane_result
    }
}

define-command nnn-picker -params 0..1 -docstring "Open nnn file explorer at the root" %{
    run-in-pane %sh{
        dir="${1:-.}"
        printf "nnn %q -d -p -\n" "$dir"
    }
    try %{
        edit -existing %opt{run_in_pane_result}
        unset-option buffer run_in_pane_result
    }
}

define-command nnn-current-directory -docstring "Open nnn file explorer at the current directory" %{
    evaluate-commands %sh{
        dir=$(dirname "$kak_buffile")
        printf "nnn-picker '%s'\n" "$dir"
    }
}

define-command tmux-split-window -docstring "Tmux split window right/down" -params 1 %{
    evaluate-commands %sh{
        tmux split-window "$1" kak -c "$kak_session" 
    }
}

define-command fzf-search -docstring "Search files using rg+fzf and open match" %{
    run-in-pane %sh{
        cat <<'EOF'
rg . -n --color=always | \
fzf --ansi --delimiter=: \
--bind 'page-up:preview-page-up,page-down:preview-page-down' \
--preview 'tail +{2} {1}'
EOF
    }
    evaluate-commands %sh{
        result="$kak_opt_run_in_pane_result"
        [ -z "$result" ] && exit 0
        IFS=: read -r file line _ <<< "$result"
        file=$(printf %s "$file" | sed "s/'/'\\\\''/g")
        line=$(printf %s "$line" | sed "s/'/'\\\\''/g")
        printf "edit -existing '%s' '%s'\n" "$file" "$line"
    }
}

# Source: https://phaazon.net/blog/kakoune-philosophy
define-command -override my-surround-add -params 2 %{
  evaluate-commands -draft -save-regs '"' %{
    set-register '"' %arg{1}
    execute-keys -draft P
    set-register '"' %arg{2}
    execute-keys -draft p
  }
}

declare-user-mode tmux
declare-user-mode match
map global user f -docstring "Search files using fzf and open match" ":fzf-file<ret>"
map global user / -docstring "Fuzzy-search text using rg+fzf and open match" ":fzf-search<ret>"
map global user n -docstring "Open nnn and select files" ":nnn-picker<ret>"
map global user . -docstring "Open nnn and select files in current directory" ":nnn-current-directory<ret>"
map global user t -docstring "Enter tmux mode" ":enter-user-mode tmux<ret>"
map global user g -docstring "Open lazygit" ":run-in-pane lazygit<ret>"
map global tmux s -docstring "Split window vertically" ":tmux-split-window -v<ret>"
map global tmux v -docstring "Split window horizontally" ":tmux-split-window -h<ret>"
map global match  m m -docstring "select to the next sequence enclosed by matching characters, see the matching_pairs option in :doc options"
map global match  M M -docstring "extend the current selection to the next sequence enclosed by matching character, see the matching_pairs option in :doc options"
map global match  <a-m> <a-m> -docstring "select to the previous sequence enclosed by matching characters, see the matching_pairs option in :doc options"
map global match  <a-M> <a-M> -docstring "extend the current selection to the previous sequence enclosed by matching characters, see the matching_pairs option in :doc options"
map global normal m '<esc>:enter-user-mode match<ret>'

map global match (   ':my-surround-add ( )<ret>'         -docstring 'surround with parenthesis'
map global match )   ':my-surround-add ( )<ret>'         -docstring 'surround with parenthesis'
map global match [   ':my-surround-add [ ]<ret>'         -docstring 'surround with brackets'
map global match ]   ':my-surround-add [ ]<ret>'         -docstring 'surround with brackets'
map global match {   ':my-surround-add { }<ret>'         -docstring 'surround with curly brackets'
map global match }   ':my-surround-add { }<ret>'         -docstring 'surround with curly brackets'
map global match <   ':my-surround-add < ><ret>'         -docstring 'surround with angle brackets'
map global match >   ':my-surround-add < ><ret>'         -docstring 'surround with angle brackets'
map global match "'" ":my-surround-add ""'"" ""'""<ret>" -docstring 'surround with quotes'
map global match '"' ":my-surround-add '""' '""'<ret>"   -docstring 'surround with double quotes'
map global match *   ':my-surround-add * *<ret>'         -docstring 'surround with asteriks'
map global match _   ':my-surround-add _ _<ret>'         -docstring 'surround with undescores'

add-highlighter global/ number-lines -relative -hlcursor
set-option global ui_options terminal_assistant=cat

try %{
    evaluate-commands %sh{kak-lsp}
    map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
    map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
    map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
    map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
    map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
    map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
    map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
    map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'
    map global user k ':lsp-hover<ret>' -docstring "LSP: show info for current position"

    hook -group lsp-filetype-python global BufSetOption filetype=python %{
        set-option buffer lsp_servers %{
            [basedpyright-langserver]
            root_globs = ["requirements.txt", "setup.py", "pyproject.toml", "pyrightconfig.json", ".git", ".hg"]
            args = ["--stdio"]
        }
    }
    lsp-inlay-hints-enable global
    lsp-inlay-diagnostics-enable global
    set-option global lsp_hover_anchor true
    lsp-enable
}

try %{
    evaluate-commands %sh{ kak-tree-sitter -dks --init $kak_session }
}

source "%val{config}/jump_mode.kak"

hook global WinCreate .* %{
    evaluate-commands %sh{
        if [ $kak_buffile != $kak_bufname ] && git ls-files --error-unmatch "$kak_buffile" > /dev/null 2>&1; then
            echo "git show-diff"
        fi
    }
}
hook global BufWritePost .* "git update-diff"
hook global BufReload .* "git update-diff"

set-option global tabstop 4
set-option global indentwidth 4

hook global WinSetOption filetype=(javascript|javascriptreact|typescript|typescriptreact) %{
    set-option window tabstop 2
    set-option window indentwidth 2
}

map -docstring 'jump (select mode: replace)' global goto w '<esc>:enter_jump_mode_with_replace_select_mode<ret>'
map -docstring 'jump (select mode: extend)' global goto W '<esc>:enter_jump_mode_with_extend_select_mode<ret>'
map -docstring 'jump (select mode: append)' global goto <a-w> '<esc>:enter_jump_mode_with_append_select_mode<ret>'

map global normal '#' ":comment-line<ret>"
map global normal <a-#> ":comment-block<ret>"

colorscheme tinty
