#!/usr/bin/env python3

import sys
import os
from urllib.parse import urlparse

sys.path.append(os.getenv('QUTE_CONFIG_DIR'))

from machine_specific_config import LIBPROXY_DOMAIN

def exec_command(cmd):
    with open(os.getenv('QUTE_FIFO'), 'w') as fifo:
        fifo.write(cmd + '\n')

def replace_netloc(netloc):
    new_netloc = "-".join(netloc.split("."))
    return f"{new_netloc}.{LIBPROXY_DOMAIN}"

o = urlparse(os.getenv("QUTE_URL"))
new_url = o._replace(netloc=replace_netloc(o.netloc)).geturl()

exec_command(f"open {new_url}")
